// v3/internal/templates/preact/frontend/src/app.jsx
import { useState, useEffect } from 'preact/hooks'
import {Greet} from "../bindings/main/GreetService.js";
import {Events} from "@wailsio/runtime";

export function App() {
  const [name, setName] = useState('');
  const [result, setResult] = useState('Please enter your name below 👇');
  const [time, setTime] = useState('Listening for Time event...');

  const doGreet = () => {
    let localName = name;
    if (!localName) {
      localName = 'anonymous';
    }
    Greet(localName).then((resultValue) => {
      setResult(resultValue);
    }).catch((err) => {
      console.log(err);
    });
  }

  useEffect(() => {
    Events.On('time', (timeValue) => {
      setTime(timeValue.data);
    });
  }, []);

  return (
    <div className="container">
      <div>
        <a wml-openURL="https://wails.io">
          <img src="/wails.png" className="logo" alt="Wails logo"/>
        </a>
        <a wml-openURL="https://preactjs.com">
          <img src="/preact.svg" className="logo preact" alt="Preact logo"/>
        </a>
      </div>
      <h1>Wails + Preact</h1>
      <div className="result">{result}</div>
      <div className="card">
        <div className="input-box">
          <input className="input" value={name} onInput={(e) => setName(e.target.value)} type="text" autoComplete="off"/>
          <button className="btn" onClick={doGreet}>Greet</button>
        </div>
      </div>
      <div className="footer">
        <div><p>Click on the Wails logo to learn more</p></div>
        <div><p>{time}</p></div>
      </div>
    </div>
  )
}

// v3/internal/templates/solid/frontend/src/App.jsx
import { createSignal, onMount } from 'solid-js'
import {Greet} from "../bindings/main/GreetService.js";
import {Events} from "@wailsio/runtime";

function App() {
  const [name, setName] = createSignal('');
  const [result, setResult] = createSignal('Please enter your name below 👇');
  const [time, setTime] = createSignal('Listening for Time event...');

  const doGreet = () => {
    let localName = name();
    if (!localName) {
      localName = 'anonymous';
    }
    Greet(localName).then((resultValue) => {
      setResult(resultValue);
    }).catch((err) => {
      console.log(err);
    });
  }

  onMount(() => {
    Events.On('time', (timeValue) => {
      setTime(timeValue.data);
    });
  });

  return (
    <div className="container">
      <div>
        <a wml-openURL="https://wails.io">
          <img src="/wails.png" className="logo" alt="Wails logo"/>
        </a>
        <a wml-openURL="https://solidjs.com">
          <img src="/solid.svg" className="logo solid" alt="Solid logo"/>
        </a>
      </div>
      <h1>Wails + Solid</h1>
      <div className="result">{result()}</div>
      <div className="card">
        <div className="input-box">
          <input className="input" value={name()} onInput={(e) => setName(e.target.value)} type="text" autocomplete="off"/>
          <button className="btn" onClick={doGreet}>Greet</button>
        </div>
      </div>
      <div className="footer">
        <div><p>Click on the Wails logo to learn more</p></div>
        <div><p>{time()}</p></div>
      </div>
    </div>
  )
}

export default App
