// cmd/templates/svelte/frontend/src/components/HelloWorld.svelte
<script>
	import { getContext } from 'svelte';
	import ModalContent from './ModalContent.svelte'
	
	const { open } = getContext('simple-modal');

	const handleOpenModal = () => {
		window.backend.basic().then((result) => {
			open(ModalContent, { message: result });
		});
	};
</script>

<main>
	<p><button on:click={handleOpenModal}>Hello</button></p>
</main>

<style></style>

// cmd/templates/create-react-app/frontend/src/components/HelloWorld.js
import React, { useState } from 'react';
import Modal from 'react-modal';

function HelloWorld() {
	const [showModal, setShowModal] = useState(false);
	const [result, setResult] = useState(null);

	const handleOpenModal = () => {
		setShowModal(true);

		window.backend.basic().then((result) => setResult(result));
	};

	const handleCloseModal = () => {
		setShowModal(false);
	};

	return (
		<div className="App">
			<button onClick={() => handleOpenModal()} type="button">
				Hello
      </button>
			<Modal
				appElement={document.getElementById("app")}
				isOpen={showModal}
				contentLabel="Minimal Modal Example"
			>
				<p>{result}</p>
				<button onClick={() => handleCloseModal()}>Close Modal</button>
			</Modal>
		</div>
	);
}

export default HelloWorld;
