// v3/internal/templates/preact-ts/frontend/src/app.tsx
import {useEffect, useState} from 'preact/hooks'
import {GreetService} from "../bindings/changeme";
import {Events} from "@wailsio/runtime";

export function App() {
    const [name, setName] = useState<string>('');
    const [result, setResult] = useState<string>('Please enter your name below 👇');
    const [time, setTime] = useState<string>('Listening for Time event...');

    const doGreet = (): void => {
        let localName = name;
        if (!localName) {
            localName = 'anonymous';
        }
        GreetService.Greet(localName).then((resultValue: string) => {
            setResult(resultValue);
        }).catch((err: any) => {
            console.log(err);
        });
    }

    useEffect(() => {
        Events.On('time', (timeValue: any) => {
            setTime(timeValue.data);
        });
    }, []);

    return (
        <>
            <div className="container">
                <div>
                    <a data-wml-openURL="https://wails.io">
                        <img src="/wails.png" className="logo" alt="Wails logo"/>
                    </a>
                    <a data-wml-openURL="https://preactjs.com">
                        <img src="/preact.svg" className="logo preact" alt="Preact logo"/>
                    </a>
                </div>
                <h1>Wails + Preact</h1>
                <div className="result">{result}</div>
                <div className="card">
                    <div className="input-box">
                        <input className="input" value={name} onInput={(e) => setName(e.currentTarget.value)}
                               type="text" autocomplete="off"/>
                        <button className="btn" onClick={doGreet}>Greet</button>
                    </div>
                </div>
                <div className="footer">
                    <div><p>Click on the Wails logo to learn more</p></div>
                    <div><p>{time}</p></div>
                </div>
            </div>
        </>
    )
}

// v3/internal/templates/solid-ts/frontend/src/App.tsx
import { createSignal, onMount } from 'solid-js'
import {GreetService} from "../bindings/changeme";
import {Events} from "@wailsio/runtime";

function App() {
  const [name, setName] = createSignal('');
  const [result, setResult] = createSignal('Please enter your name below 👇');
  const [time, setTime] = createSignal('Listening for Time event...');

  const doGreet = () => {
    let localName = name();
    if (!localName) {
      localName = 'anonymous';
    }
    GreetService.Greet(localName).then((resultValue: string) => {
      setResult(resultValue);
    }).catch((err: any) => {
      console.log(err);
    });
  }

  onMount(() => {
    Events.On('time', (timeValue: any) => {
      setTime(timeValue.data);
    });
  });

  return (
    <div class="container">
      <div>
        <a data-wml-openURL="https://wails.io">
          <img src="/wails.png" class="logo" alt="Wails logo"/>
        </a>
        <a data-wml-openURL="https://solidjs.com">
          <img src="/solid.svg" class="logo solid" alt="Solid logo"/>
        </a>
      </div>
      <h1>Wails + Solid</h1>
      <div class="result">{result()}</div>
      <div class="card">
        <div class="input-box">
          <input class="input" value={name()} onInput={(e) => setName(e.currentTarget.value)} type="text" autocomplete="off"/>
          <button class="btn" onClick={doGreet}>Greet</button>
        </div>
      </div>
      <div class="footer">
        <div><p>Click on the Wails logo to learn more</p></div>
        <div><p>{time()}</p></div>
      </div>
    </div>
  )
}

export default App
