// v3/internal/templates/react/frontend/src/App.jsx
import { useState, useEffect } from 'react'
import {GreetService} from "../bindings/changeme";
import {Events, WML} from "@wailsio/runtime";

function App() {
  const [name, setName] = useState('');
  const [result, setResult] = useState('Please enter your name below 👇');
  const [time, setTime] = useState('Listening for Time event...');

  const doGreet = () => {
    let localName = name;
    if (!localName) {
      localName = 'anonymous';
    }
    GreetService.Greet(localName).then((resultValue) => {
      setResult(resultValue);
    }).catch((err) => {
      console.log(err);
    });
  }

  useEffect(() => {
    Events.On('time', (timeValue) => {
      setTime(timeValue.data);
    });
    // Reload WML so it picks up the wml tags
    WML.Reload();
  }, []);

  return (
    <div className="container">
      <div>
        <a data-wml-openURL="https://wails.io">
          <img src="/wails.png" className="logo" alt="Wails logo"/>
        </a>
        <a data-wml-openURL="https://reactjs.org">
          <img src='/react.svg' className="logo react" alt="React logo"/>
        </a>
      </div>
      <h1>Wails + React</h1>
      <div className="result">{result}</div>
      <div className="card">
        <div className="input-box">
          <input className="input" value={name} onChange={(e) => setName(e.target.value)} type="text" autoComplete="off"/>
          <button className="btn" onClick={doGreet}>Greet</button>
        </div>
      </div>
      <div className="footer">
        <div><p>Click on the Wails logo to learn more</p></div>
        <div><p>{time}</p></div>
      </div>
    </div>
  )
}

export default App

// v3/internal/templates/qwik/frontend/src/app.jsx
import { component$, useSignal, useVisibleTask$ } from '@builder.io/qwik'
import {GreetService} from "../bindings/changeme";
import {Events, WML} from "@wailsio/runtime";

export const App = component$(() => {
  const name = useSignal('');
  const result = useSignal('Please enter your name below 👇');
  const time = useSignal('Listening for Time event...');

  const doGreet = () => {
    let localName = name.value;
    if (!localName) {
      localName = 'anonymous';
    }
    GreetService.Greet(localName).then((resultValue) => {
      result.value = resultValue;
    }).catch((err) => {
      console.log(err);
    });
  }

  useVisibleTask$(() => {
    Events.On('time', (timeValue) => {
      time.value = timeValue.data;
    });
    // Reload WML so it picks up the wml tags
    WML.Reload();
  });

  return (
    <div class="container">
      <div>
        <a data-wml-openURL="https://wails.io">
          <img src="/wails.png" class="logo" alt="Wails logo"/>
        </a>
        <a data-wml-openURL="https://qwik.builder.io">
          <img src="/qwik.svg" class="logo qwik" alt="Qwik logo"/>
        </a>
      </div>
      <h1>Wails + Qwik</h1>
      <div class="result">{result.value}</div>
      <div class="card">
        <div class="input-box">
          <input class="input" value={name.value} onInput$={(e) => name.value = e.target.value} type="text" autocomplete="off"/>
          <button class="btn" onClick$={doGreet}>Greet</button>
        </div>
      </div>
      <div class="footer">
        <div><p>Click on the Wails logo to learn more</p></div>
        <div><p>{time.value}</p></div>
      </div>
    </div>
  )
})
